version: '2'

services:

  wekandb:
    image: mongo:3.2.18
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: dpoz/wekan:latest
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - METEOR_RELEASE=${METEOR_RELEASE}
        - NPM_VERSION=${NPM_VERSION}
        - ARCHITECTURE=${ARCHITECTURE}
        - SRC_PATH=${SRC_PATH}
        - METEOR_EDGE=${METEOR_EDGE}
        - USE_EDGE=${USE_EDGE}
    expose:
      - 80
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost
    depends_on:
      - wekandb

  sslproxy:
    image: danieldent/nginx-ssl-proxy
    container_name: wekan-ssl-proxy
    restart: always
    networks:
      - wekan-tier
    depends_on:
      - wekan
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
    environment:
      UPSTREAM: wekan:80
      SERVERNAME: TYPE-HERE
      # EXTRANAMES: www.test.example.com,test2.example.com

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
