version: 1
jobs:
  build:
    machine: true
    steps:
      # - setup_remote_docker
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker-compose -f docker-compose-build.yml build
      - run: |
          destination=preview
          version=2.$CIRCLE_BUILD_NUM-ci-upstream-preview
          docker tag dpoz/wekan:$destination dpoz/wekan:$version
          docker push dpoz/wekan:$destination

      #https://circleci.com/docs/2.0/building-docker-images/
